local ctx = require("hyprconf.context")

local M = {}

local function bool(value)
  return value and "1" or "0"
end

function M.setup()
  local noctalia = ctx.noctalia_shell or {}
  local path = ctx.config_dir .. "/.hypr-runtime.env"
  local file, err = io.open(path, "w")

  if not file then
    print(
      "[WARN] Unable to write runtime config " .. path .. ": " .. tostring(err)
    )
    return
  end

  file:write("# Generated by lua/hyprconf/runtime.lua\n")
  file:write("NOCTALIA_SHELL_ENABLED=", bool(noctalia.enabled), "\n")
  file:close()
end

return M
