[dev]
label = "Development Fundamentals"
pacman = [
  "git",
  "gnupg",
  "npm",
  "pass",
]
aur = [
  "git-credential-manager-bin",
]

[docker]
label = "Docker"
explicit_only = true
pacman = [
  "docker",
  "docker-compose",
  "docker-buildx",
]
aur = [
  "lazydocker-bin",
]

[neovim]
label = "Neovim Editor"
pacman = [
  "lazygit",
  "neovim",
  "tree-sitter-cli",
]
