[shell]
label = "Shell & Prompt"
pacman = [
  "zsh",
  "zsh-completions",
  "gum",
  "lsd",
  "fastfetch",
]

[cli-tools]
label = "CLI Tools"
pacman = [
  "fzf",
  "fd",
  "thefuck",
  "tldr",
  "eza",
  "bat",
  "tar",
  "curl",
  "git-delta",
  "btop",
  "cava",
  "bc",
  "jq",
  "chafa",
  "rsync",
  "wget",
  "unzip",
  "7zip",
]

[terminal]
label = "Terminals"
pacman = [
  "kitty",
  "ghostty",
]
