[audio]
label = "Audio Services"
pacman = [
  "pipewire",
  "pipewire-alsa",
  "pipewire-audio",
  "pipewire-pulse",
  "wireplumber",
  "pavucontrol",
  "playerctl",
]

[credentials]
label = "Credential Storage"
pacman = [
  "keepassxc",
]

[bluetooth]
label = "Bluetooth"
pacman = [
  "bluez",
  "bluez-utils",
  "blueman",
]

[network]
label = "NetworkManager"
pacman = [
  "networkmanager",
  "network-manager-applet",
  "nm-connection-editor",
]

[network-tools]
label = "Network Sharing & Diagnostics"
pacman = [
  "dnsmasq",
  "hostapd",
  "mtr",
  "ufw",
]

[realtime]
label = "Realtime Audio"
pacman = [
  "realtime-privileges",
  "rt-tests",
  "rtirq",
  "schedtool",
  "tuna",
]

[system-tools]
label = "System Utilities"
pacman = [
  "pacman-contrib",
  "nvtop",
  "baobab",
  "inxi",
  "i2c-tools",
]

[vpn]
label = "VPN"
pacman = [
  "networkmanager-openconnect",
  "networkmanager-openvpn",
  "tailscale",
]

[monitor]
label = "Monitor"
pacman = [
  # NOTE: this util needs i2c-tools to get work.
  # i2c-tools will auto-load the i2c-dev module.
  # refs:
  # https://wiki.archlinux.org/title/I2C
  # https://bugs.archlinux.org/task/76233
  "ddcutil",
]
