[git-shell]
paths = [
  "README.md",
  ".dotfiles-repo",
  "doc",
  "assets",
  ".gitconfig",
  ".gitattributes",
  ".gitmodules",
  ".gitignore",
  ".editorconfig",
  ".agents",
  "AGENTS.md",
]

[homebase]
paths = [
  ".config/homebase",
  ".local/libexec/homebase",
]

[zsh]
paths = [
  ".zshrc",
  ".zprofile",
  ".p10k.zsh",
]

[gtk]
paths = [
  ".config/gtk-3.0",
  ".config/gtk-4.0",
]

[apps]
paths = [
  ".config/nvim",
  ".config/kitty",
  ".config/electron-flags.conf",
  ".config/hypr",
  ".config/Kvantum",
  ".config/quickshell",
  ".config/btop",
  ".config/fastfetch",
  ".config/qt5ct",
  ".config/qt6ct",
  ".config/swappy",
  ".config/vesktop/settings",
  ".config/vesktop/themes",
  ".config/vesktop/settings.json",
  ".config/cava",
  ".config/ghostty",
  ".config/sunshine/sunshine.conf",
  ".config/polychromatic/preferences.json",
  ".config/openrazer",
]

[systemd-user]
paths = [
  ".config/autostart/remmina-applet.desktop",
  ".config/systemd/user/sunshine.service.d",
  ".config/systemd/user/openrazer-daemon.service.d/delay.conf",
  ".config/systemd/user/noctalia.service",
  ".config/systemd/user/quickshell-overview.service",
  ".config/systemd/user/polychromatic-tray.service",
  ".config/systemd/user/keepassxc.service",
  ".config/systemd/user/keepassxc-tray-refresh.service",
  ".config/systemd/user/remmina-applet.service",
  ".config/systemd/user/tailscale-systray.service",
  ".config/systemd/user/vesktop.service",
  ".config/systemd/user/directory-backup.service",
  ".config/systemd/user/directory-backup.timer",
  ".config/directory-backup",
  ".local/bin/directory-backup",
]

[onedrive]
paths = [
  ".config/onedrive/config",
  ".config/onedrive/sync_list",
]

[desktop]
paths = [
  ".local/state/noctalia/settings.toml",
  "Pictures/Wallpapers",
]
