local ctx = require("hyprconf.context")
local json = require("hyprconf.json")

local M = {}

local paths = {
  colors = ctx.home .. "/.config/noctalia/colors.json",
  wallpapers = ctx.home .. "/.cache/noctalia/wallpapers.json",
  qml = ctx.home .. "/.config/quickshell/qml_color.json",
  rofi = ctx.home .. "/.config/rofi/wallust/colors-rofi.rasi",
  generated = ctx.config_dir .. "/lua/hyprconf/generated/noctalia.lua",
  wallpaper_effects = ctx.config_dir .. "/wallpaper-effects",
}

local material_keys = {
  "mSurface",
  "mSurfaceVariant",
  "mOnSurface",
  "mOnSurfaceVariant",
  "mPrimary",
  "mSecondary",
  "mTertiary",
  "mError",
  "mOnPrimary",
  "mOnSecondary",
  "mOutline",
  "mShadow",
}

local qml_order = {
  "windowBackground",
  "primaryText",
  "layerBackground1",
  "layerBackground2",
  "layerBackground3",
  "surfaceText",
  "secondaryText",
  "borderPrimary",
  "shadowColor",
  "accentPrimary",
  "accentSecondary",
  "selectionBackground",
  "accentPrimaryText",
  "selectionText",
  "borderSecondary",
}

local function shell_quote(value)
  return "'" .. tostring(value):gsub("'", "'\\''") .. "'"
end

local function mkdir_parent(path)
  local parent = path:match("(.+)/[^/]+$")
  if parent then
    os.execute("mkdir -p " .. shell_quote(parent))
  end
end

local function write_file(path, content)
  mkdir_parent(path)
  local file = assert(io.open(path, "w"))
  file:write(content)
  file:close()
end

local function notify(summary, body, urgency)
  local cmd = "notify-send"
  if urgency then
    cmd = cmd .. " -u " .. shell_quote(urgency)
  end
  cmd = cmd .. " " .. shell_quote(summary) .. " " .. shell_quote(body or "")
  os.execute(cmd .. " >/dev/null 2>&1 || true")
end

local function hex_to_rgb(value)
  local hex = tostring(value or ""):match("#?(%x%x%x%x%x%x)")
  return hex and ("rgb(" .. hex .. ")") or "rgb(000000)"
end

local function load_material_colors(path)
  local content = json.read(path)
  local colors = {}

  for _, key in ipairs(material_keys) do
    colors[key] = json.string_field(content, key)
  end

  return colors
end

local function generate_qml(colors)
  return json.encode_object({
    windowBackground = colors.mSurface,
    primaryText = colors.mOnSurface,
    layerBackground1 = colors.mPrimary,
    layerBackground2 = colors.mSurfaceVariant,
    layerBackground3 = colors.mShadow,
    surfaceText = colors.mOnSurface,
    secondaryText = colors.mOnSurfaceVariant,
    borderPrimary = colors.mPrimary,
    shadowColor = colors.mShadow,
    accentPrimary = colors.mPrimary,
    accentSecondary = colors.mSecondary,
    selectionBackground = colors.mPrimary,
    accentPrimaryText = colors.mOnPrimary,
    selectionText = colors.mOnPrimary,
    borderSecondary = colors.mOutline,
  }, qml_order)
end

local function generate_rofi(colors)
  return string.format(
    [[/* noctalia Material Design theme - generated by Lua */

* {
active-background: %s;
active-foreground: %s;
normal-background: %s;
normal-foreground: %s;
urgent-background: %s;
urgent-foreground: %s;

alternate-active-background: %s;
alternate-active-foreground: %s;
alternate-normal-background: %s;
alternate-normal-foreground: %s;
alternate-urgent-background: %s;
alternate-urgent-foreground: %s;

selected-active-background: %s;
selected-active-foreground: %s;
selected-normal-background: %s;
selected-normal-foreground: %s;
selected-urgent-background: %s;
selected-urgent-foreground: %s;

background-color: %s;
background: rgba(0,0,0,0.85);
foreground: %s;
border-color: %s;

color0: %s;
color1: %s;
color2: %s;
color3: %s;
color4: %s;
color5: %s;
color6: %s;
color7: %s;
color8: %s;
color9: %s;
color10: %s;
color11: %s;
color12: %s;
color13: %s;
color14: %s;
color15: %s;
}
]],
    colors.mPrimary,
    colors.mOnPrimary,
    colors.mSurface,
    colors.mOnSurface,
    colors.mError,
    colors.mOnPrimary,
    colors.mSurfaceVariant,
    colors.mOnSurface,
    colors.mSurface,
    colors.mOnSurface,
    colors.mSurface,
    colors.mOnSurface,
    colors.mPrimary,
    colors.mOnPrimary,
    colors.mPrimary,
    colors.mOnPrimary,
    colors.mSurfaceVariant,
    colors.mOnPrimary,
    colors.mSurface,
    colors.mOnSurface,
    colors.mPrimary,
    colors.mSurface,
    colors.mShadow,
    colors.mSurfaceVariant,
    colors.mOutline,
    colors.mSurfaceVariant,
    colors.mOutline,
    colors.mSurfaceVariant,
    colors.mPrimary,
    colors.mSurfaceVariant,
    colors.mShadow,
    colors.mOutline,
    colors.mSecondary,
    colors.mPrimary,
    colors.mError,
    colors.mTertiary,
    colors.mOnSurface
  )
end

local function generate_hypr_colors(colors)
  return string.format(
    [[-- Generated by scripts/display/noctalia-theme.lua
return {
    primary = %q,
    surface = %q,
    secondary = %q,
    error = %q,
    tertiary = %q,
    surface_lowest = %q,
}
]],
    hex_to_rgb(colors.mPrimary),
    hex_to_rgb(colors.mSurface),
    hex_to_rgb(colors.mSecondary),
    hex_to_rgb(colors.mError),
    hex_to_rgb(colors.mTertiary),
    hex_to_rgb(colors.mShadow)
  )
end

local function current_wallpaper()
  local file = io.open(paths.wallpapers, "r")
  if not file then
    return nil
  end

  local content = file:read("*a")
  file:close()
  return json.object_string_field(content, "wallpapers", "")
    or json.object_string_field(content, "wallpapers", "HDMI-A-1")
end

local function sync_wallpaper_effects(colors)
  local wallpaper = current_wallpaper()
  if not wallpaper then
    return
  end

  local probe = io.open(wallpaper, "r")
  if not probe then
    return
  end
  probe:close()

  os.execute("mkdir -p " .. shell_quote(paths.wallpaper_effects))
  os.execute(
    "cp -f "
      .. shell_quote(wallpaper)
      .. " "
      .. shell_quote(paths.wallpaper_effects .. "/.wallpaper_current")
  )

  local cmd = table.concat({
    "magick",
    shell_quote(wallpaper),
    "-blur 0x18",
    "-fill " .. shell_quote(colors.mSurface),
    "-colorize 30",
    "-quality 90",
    shell_quote(paths.wallpaper_effects .. "/.wallpaper_modified"),
  }, " ")
  os.execute(cmd .. " >/dev/null 2>&1 || true")
end

function M.apply()
  local ok, colors = pcall(load_material_colors, paths.colors)
  if not ok then
    notify(
      "Noctalia Theme",
      paths.colors .. " not found or unreadable",
      "critical"
    )
    return false
  end

  write_file(paths.qml, generate_qml(colors))
  write_file(paths.rofi, generate_rofi(colors))
  write_file(paths.generated, generate_hypr_colors(colors))
  sync_wallpaper_effects(colors)

  os.execute("hyprctl reload config-only >/dev/null 2>&1 || true")
  notify(
    "Noctalia Theme",
    "Applied Material Design colors to rofi, quickshell, and Hyprland."
  )
  return true
end

return M
