schema_version = 1

[platform]
active = "auto"

[platform.aliases]
arch = "archlinux"
manjaro = "archlinux"

[dotfiles]
ssh_url = "git@github.com:gin31259461/dotfiles-arch.git"
https_url = "https://github.com/gin31259461/dotfiles-arch.git"
git_dir = "~/.dotfiles"
branch = "main"
state_file = "~/.dotfiles-repo"

[packages]
official_manager = "pacman"
aur_helper = "yay"

[bootstrap]
packages = [
  "git",
  "rsync",
  "base-devel",
  "go",
  "ca-certificates",
  "lsd",
  "zsh",
  "openssh",
]
