config_version = 12

[bar.default]
background_opacity = 0.0
capsule = true
capsule_border = "outline"
capsule_radius = 26
capsule_thickness = 0.89999998360872269
end = [ "media", "tray", "group:g1" ]
margin_edge = 2
margin_ends = 14
shadow = false
start = [ "group:g2", "workspaces" ]
thickness = 36

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    border = "outline"
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "notifications", "control-center", "session" ]
    opacity = 1.0
    padding = 14.0
    widget_spacing = 14

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    border = "outline"
    enabled = true
    fill = "surface_variant"
    id = "g2"
    members = [ "launcher", "wallpaper", "mpvpaper" ]
    opacity = 1.0
    padding = 14.0
    widget_spacing = 14

[brightness]
enable_ddcutil = true
minimum_brightness = 0.19999999552965164
sync_all_monitors = true

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[lockscreen]
blur_intensity = 0.0

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@FALLBACK", "lockscreen-login-box@HDMI-A-1", "lockscreen-widget-0000000000000001" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@FALLBACK"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "FALLBACK"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@FALLBACK".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 488.0
    cy = 954.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 160.0
    box_width = 288.0
    cx = 352.0
    cy = 252.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        center_text = false
        clock_style = "digital"

[osd.kinds]
keyboard_layout = false
lock_keys = false
media = false

[plugin_settings."noctalia/mpvpaper"]
extract_last_frame = false
picker_placement = "floating"
picker_position = "center"
video_directory = "/home/abnertu/Videos/Wallpapers"

[plugins]
enabled = []

[shell]
clipboard_enabled = false

    [shell.panel]
    clipboard_position = "auto"
    control_center_placement = "floating"
    open_near_click_clipboard = true
    open_near_click_control_center = true
    open_near_click_session = true
    session_placement = "floating"
    wallpaper_placement = "floating"
    wallpaper_position = "center"

[theme]
builtin = "Tokyo-Night"
community_palette = "Tokyo Night Moon"
mode = "dark"
source = "builtin"
wallpaper_scheme = "soft"

    [theme.templates]
    builtin_ids = [ "btop", "cava", "gtk3", "gtk4", "hyprland", "kitty", "qt" ]
    community_ids = [ "zen-browser", "bat", "discord", "lazygit", "steam", "hyprtoolkit" ]

[wallpaper.default]
path = "/home/abnertu/Pictures/Wallpapers/arch-building-with-girl-5.png"

[wallpaper.last]
path = "/home/abnertu/Pictures/Wallpapers/arch-building-with-girl-5.png"

[wallpaper.monitors.FALLBACK]
path = "/home/abnertu/.cache/noctalia/mpvpaper/_home_abnertu_Videos_Wallpapers_arch_building_girl_gwr_video_seamless_mp4.jpg"

[wallpaper.monitors.HDMI-A-1]
path = "/home/abnertu/Pictures/Wallpapers/arch-building-with-girl-5.png"

[widget.clock]
format = "{:%D  %H:%M}"

[widget.control-center]
glyph = "hyprland"

[widget.launcher]
glyph = "apps-filled"

[widget.mpvpaper]
type = "noctalia/mpvpaper:mpvpaper"
